### ISSUE TITLE
Description editor's link creator/editor does not work

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#1]
When trying to insert/modify links  via the description editor, "nothing" happens in the UI and the following errors are printed to console:

```
script-fi.js?1525255475:7732 GET https://kirkanta.kirjastot.fi/organisation/plugins/link/dialogs/link.js?t=G6DD net::ERR_ABORTED 404 (Not Found)

script-fi.js?1525255475:8229 Uncaught Error: [CKEDITOR.dialog.openDialog] Dialog "link" failed when loading definition.
    at a.openDialog (script-fi.js?1525255475:8229)
    at a.<anonymous> (script-fi.js?1525255475:8229)
    at g (script-fi.js?1525255475:7872)
    at Array.n (script-fi.js?1525255475:7873)
    at v (script-fi.js?1525255475:7873)
    at HTMLScriptElement.CKEDITOR.env.ie.CKEDITOR.env.version.f.$.onerror (script-fi.js?1525255475:7874)
```
![image](https://user-images.githubusercontent.com/42733913/47219990-1afd0480-d3b9-11e8-8d08-23049d390f9e.png)

Edit: I think this has been broken for longer than a month, so it's unlikely related to recent changes, if any were made.

**Comment by sjuvonen** [comment]
This bug report concerned the old version of Kirkanta and not this active development version. Since Kirkanta has been upgraded to use code from this repository, the bug has also become fixed.
