### ISSUE TITLE
Staff phone number is required and thus cannot be saved without one anymore.

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#13]
When editing a person and leaving phone number blank or entering a "invalid value" (such as -) results in being unable to save/update the contact due to a validation error.

![image](https://user-images.githubusercontent.com/42733913/60795271-0b566380-a174-11e9-9d0c-253cb544023f.png)

From dev console: "106390:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)"

**Comment by humble-ahitofel** [comment]
Hi Olli,
I asked about this of our few content managers and it seems, that phone number should not be a  required field.
I'll try to get this fixed when I have the time, but for now, I'll mark this as a bug.
