### ISSUE TITLE
If - is used in phone number, validation fails.

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#15]
Users may want to enter their phone in eq. xxx-xxxx-xxx format, apparently this is not supported anymore, as a validation error was triggered when trying to save the contact after changing their email.

![image](https://user-images.githubusercontent.com/42733913/60887988-682e4880-a25e-11e9-827e-aee3a59c7e70.png)

**Comment by sjuvonen** [comment]
Maybe the input field could accept values in varying formats but in the end the phone number will be normalized to a standard form anyways. Phone numbers are formatted as per national recommendation and not open for users' own interpretation.

**Comment by sjuvonen** [comment]
Fixed with 66a3429.
