### ISSUE TITLE
Login errors are shown as "code"

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#2]
https://kirkanta.kirjastot.fi/login

When invalid login details are provided, the following error is shown in the UI:

Symfony\Component\Security\Core\Exception\BadCredentialsException: Bad credentials. in /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php:67 Stack trace: #0 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(149): session_start() #1 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(313): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #2 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-foundation/Session/Session.php(256): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #3 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-foundation/Session/Session.php(278): Symfony\Component\HttpFoundation\Session\Session->getBag('attributes') #4 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-foundation/Session/Session.php(73): Symfony\Component\HttpFoundation\Session\Session->getAttributeBag() #5 /srv/sites/kirkanta.kirjastot.fi/src/EventListener/SessionLanguageSubscriber.php(54): Symfony\Component\HttpFoundation\Session\Session->get('uilang') #6 /srv/sites/kirkanta.kirjastot.fi/src/EventListener/SessionLanguageSubscriber.php(41): App\EventListener\SessionLanguageSubscriber->getLanguage() #7 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/event-dispatcher/EventDispatcher.php(212): App\EventListener\SessionLanguageSubscriber->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #8 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #9 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-kernel/HttpKernel.php(126): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #10 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-kernel/HttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /srv/sites/kirkanta.kirjastot.fi/vendor/symfony/http-kernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /srv/sites/kirkanta.kirjastot.fi/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 {main}

![image](https://user-images.githubusercontent.com/42733913/50584437-4354b500-0e78-11e9-8289-4c9f4a1ce73d.png)

**Comment by sjuvonen** [comment]
Fixed in https://github.com/libraries-fi/kirkanta/commit/b2a8555046de5a3e35d5906e5254bf2f26310b46.
