### ISSUE TITLE
Clicking the translations icon while editing a link triggers "Error 403 Forbidden"

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#3]
If the translations icon is pressed while editing a link, the following error is triggered:

 ”Oops! An Error Occurred
The server returned a "403 Forbidden".

https://kirkanta.kirjastot.fi/library/85159/contact/links/200694/edit

https://kirkanta.kirjastot.fi/admin/web_link/2581/translate

![image](https://user-images.githubusercontent.com/42733913/50584608-44d2ad00-0e79-11e9-8395-eefe4e81de44.png)

**Comment by sjuvonen** [comment]
Fixed in https://github.com/libraries-fi/kirkanta/commit/d91cf568c0fa810c6813e9b371d8f0cf7882c752.
