### ISSUE TITLE
Opening a parent organization results in Error 500 Internal Server Error.

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#4]
Opening a "Parent organisation" results in: 

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

Logged in as user "jyvaskyla"

https://kirkanta.kirjastot.fi/organisation/85465

**Comment by sjuvonen** [comment]
Fixed in https://github.com/libraries-fi/kirkanta/commit/571ec538f87b45a92b45995c15284bbe7a58b4c1.
