### ISSUE TITLE
New service templates are not shown in the "Service templates" list

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#5]
Steps to reproduce the issue:

1. Create a new service template.
2. Template is created, but it is not visible in the "Service templates" list

The template can however be normally added to library details.

An older service template created in V3 is shown in the list correctly (possibly because it's type is "Room"?):
https://kirkanta.kirjastot.fi/service_instance/153

![image](https://user-images.githubusercontent.com/42733913/50584985-69c81f80-0e7b-11e9-8667-46931131cf87.png)

Record was created.
Standard details
Name
Viddla elokuvapalvelu

Type
web_service
Changing these details is restricted to administrators.

![image](https://user-images.githubusercontent.com/42733913/50584983-66349880-0e7b-11e9-85cf-aaf5d31dbce1.png)

![image](https://user-images.githubusercontent.com/42733913/50584999-7ea4b300-0e7b-11e9-83b6-6fca868d4545.png)

**Comment by sjuvonen** [comment]
This was due to confusion WRT purpose of certain attributes. Fixed in https://github.com/libraries-fi/kirkanta/commit/b584b65d318d317aebc7f25db54a4a6ccbc913a1.
