### ISSUE TITLE
https://kirkanta.kirjastot.fi/library/add | Error 500

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#6]
https://kirkanta.kirjastot.fi/library/add does not work and triggers server error instead.

Tested on Chrome, FF.
Users: jyvaskyla, keski

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by sjuvonen** [comment]
Hi and sorry again, I haven't received any notifications via email. This is fixed now.
