### ISSUE TITLE
Schedule ending date cannot be removed.

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#9]
It is not possible to remove the ending date of a schedule.

This is an issue if the ending date is set to the "default" schedule in error, thus the whole "default" schedule needs to be deleted and re-entered.

The following schedule is for Kuhmoinen, I will fix it in a minute by re-creating the schedule as "default".

![image](https://user-images.githubusercontent.com/42733913/57070870-68035100-6ce1-11e9-96c3-eb541a25fe88.png)

**Comment by sjuvonen** [comment]
Fixed with https://github.com/libraries-fi/kirkanta/commit/36c3851bff7571d2740b9bf9f09509cc44d2039d
